version: '3.7'


services:
  web:
    container_name: nginx
    build: .
    ports:
      - "4200:4200"
   
    depends_on:      
      - springcommunity




  springcommunity:
    image: springcommunity/spring-petclinic-rest
    ports:
     - "9966:9966"


