version: '3.7'


services:

  springcommunity:
    image: springcommunity/spring-petclinic-rest
    ports:
     - "9966:9966" 
  
  web:
    container_name: nginx
    build: .
    ports:
      - "4200:4200"
   
    depends_on:      
      - springcommunity
    links:
      - springcommunity
    restart: always


